import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Navbar } from '@/components/navbar';
import { Footer } from '@/components/footer/Footer';
import { ToastContainer } from 'react-toastify';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div
          className='min-h-screen bg-no-repeat bg-center bg-cover bg-fixed md:pb-16 w-full bg-gradient-to-r from-[#d2e4fc] to-[#f7f7f7]'
          style={{ backgroundImage: "url('/bg.jpg')" }}
        >
          <Navbar />
          <div
            className='container lg:rounded-2xl bg-white px-4 sm:px-5 md:px-10 lg:px-20 mx-auto py-8 shadow-sm'
            style={{ maxWidth: '1332px' }}
          >
            {children}
            <Footer />
          </div>
        </div>
        <ToastContainer />
      </body>
    </html>
  );
}
